name: fitness_tracker_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Manage widgets Life cycle more efficiently
  flutter_hooks: ^0.20.5

  # hooks and riverpod in one package(pretty cool right?)
  hooks_riverpod: ^2.5.1

  # Navigation, snackbars, dialogs, etc.
  get: ^4.6.6

  # Working with Date/Time
  intl: ^0.19.0

  # State management
  flutter_riverpod: ^2.5.1

  # Animated page indicator
  smooth_page_indicator: ^1.1.0

  # Add svgs to the app
  flutter_svg: ^2.0.10+1

  # Import ready-made animations
  lottie: ^3.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# flutter_native_splash:
#   background_image: assets/pngs/splashscreen.png
#   android: true
#   ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/jpgs/
    - assets/svgs/

